# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-17 09:47
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lrs.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(db_index=True, max_length=2083, unique=True)),
                ('canonical_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(db_index=True, max_length=2083)),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('activity_id', models.CharField(db_index=True, max_length=2083)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('etag', models.CharField(blank=True, max_length=50)),
                ('json_profile', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('profile', models.FileField(null=True, upload_to=b'activity_profile')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(max_length=2083)),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('activity_id', models.CharField(db_index=True, max_length=2083)),
                ('registration_id', models.CharField(db_index=True, max_length=40)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('etag', models.CharField(blank=True, max_length=50)),
                ('json_state', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('state', models.FileField(null=True, upload_to=b'activity_state')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectType', models.CharField(blank=True, default=b'Agent', max_length=6)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('mbox', models.CharField(db_index=True, max_length=128, null=True, unique=True)),
                ('mbox_sha1sum', models.CharField(db_index=True, max_length=40, null=True, unique=True)),
                ('openid', models.CharField(db_index=True, max_length=2083, null=True, unique=True)),
                ('oauth_identifier', models.CharField(db_index=True, max_length=192, null=True, unique=True)),
                ('account_homePage', models.CharField(max_length=2083, null=True)),
                ('account_name', models.CharField(max_length=100, null=True)),
                ('member', models.ManyToManyField(related_name='_agent_member_+', to='lrs.Agent')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(db_index=True, max_length=2083)),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('etag', models.CharField(blank=True, max_length=50)),
                ('json_profile', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('profile', models.FileField(null=True, upload_to=b'agent_profile')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lrs.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('object_statementref', models.UUIDField(db_index=True, editable=False, null=True)),
                ('result_success', models.NullBooleanField()),
                ('result_completion', models.NullBooleanField()),
                ('result_response', models.TextField(blank=True)),
                ('result_duration', models.CharField(blank=True, max_length=40)),
                ('result_score_scaled', models.FloatField(blank=True, null=True)),
                ('result_score_raw', models.FloatField(blank=True, null=True)),
                ('result_score_min', models.FloatField(blank=True, null=True)),
                ('result_score_max', models.FloatField(blank=True, null=True)),
                ('result_extensions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('stored', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('voided', models.NullBooleanField(default=False)),
                ('context_registration', models.CharField(blank=True, db_index=True, max_length=40)),
                ('context_revision', models.TextField(blank=True)),
                ('context_platform', models.CharField(blank=True, max_length=50)),
                ('context_language', models.CharField(blank=True, max_length=50)),
                ('context_extensions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('context_statement', models.CharField(blank=True, max_length=40)),
                ('version', models.CharField(max_length=7)),
                ('full_statement', django.contrib.postgres.fields.jsonb.JSONField()),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_statement', to='lrs.Agent')),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority_statement', to='lrs.Agent')),
                ('context_ca_category', models.ManyToManyField(related_name='stmt_context_ca_category', to='lrs.Activity')),
                ('context_ca_grouping', models.ManyToManyField(related_name='stmt_context_ca_grouping', to='lrs.Activity')),
                ('context_ca_other', models.ManyToManyField(related_name='stmt_context_ca_other', to='lrs.Activity')),
                ('context_ca_parent', models.ManyToManyField(related_name='stmt_context_ca_parent', to='lrs.Activity')),
                ('context_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_context_instructor', to='lrs.Agent')),
                ('context_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_context_team', to='lrs.Agent')),
                ('object_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_of_statement', to='lrs.Activity')),
                ('object_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_of_statement', to='lrs.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='StatementAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('payload', models.FileField(max_length=150, null=True, storage=lrs.models.AttachmentFileSystemStorage(), upload_to=b'attachment_payloads')),
                ('statement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stmt_attachments', to='lrs.Statement')),
            ],
        ),
        migrations.CreateModel(
            name='SubStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_statementref', models.UUIDField(db_index=True, editable=False, null=True)),
                ('result_success', models.NullBooleanField()),
                ('result_completion', models.NullBooleanField()),
                ('result_response', models.TextField(blank=True)),
                ('result_duration', models.CharField(blank=True, max_length=40)),
                ('result_score_scaled', models.FloatField(blank=True, null=True)),
                ('result_score_raw', models.FloatField(blank=True, null=True)),
                ('result_score_min', models.FloatField(blank=True, null=True)),
                ('result_score_max', models.FloatField(blank=True, null=True)),
                ('result_extensions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(null=True)),
                ('context_registration', models.CharField(blank=True, db_index=True, max_length=40)),
                ('context_revision', models.TextField(blank=True)),
                ('context_platform', models.CharField(blank=True, max_length=50)),
                ('context_language', models.CharField(blank=True, max_length=50)),
                ('context_extensions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('context_statement', models.CharField(blank=True, max_length=40)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_of_substatement', to='lrs.Agent')),
                ('context_ca_category', models.ManyToManyField(related_name='sub_context_ca_category', to='lrs.Activity')),
                ('context_ca_grouping', models.ManyToManyField(related_name='sub_context_ca_grouping', to='lrs.Activity')),
                ('context_ca_other', models.ManyToManyField(related_name='sub_context_ca_other', to='lrs.Activity')),
                ('context_ca_parent', models.ManyToManyField(related_name='sub_context_ca_parent', to='lrs.Activity')),
                ('context_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substatement_context_instructor', to='lrs.Agent')),
                ('context_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substatement_context_team', to='lrs.Agent')),
                ('object_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_of_substatement', to='lrs.Activity')),
                ('object_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_of_substatement', to='lrs.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb_id', models.CharField(db_index=True, max_length=2083, unique=True)),
                ('canonical_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='substatement',
            name='verb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lrs.Verb'),
        ),
        migrations.AddField(
            model_name='statement',
            name='object_substatement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_of_statement', to='lrs.SubStatement'),
        ),
        migrations.AddField(
            model_name='statement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statement',
            name='verb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lrs.Verb'),
        ),
        migrations.AddField(
            model_name='activitystate',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lrs.Agent'),
        ),
        migrations.AddField(
            model_name='activity',
            name='authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lrs.Agent'),
        ),
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together=set([('account_homePage', 'account_name')]),
        ),
    ]
